name: Deploy to GitHub Pages
on:
    push:
        branches: 'main'
jobs:
    build_site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
            - name: Install dependencies
              run: pnpm i
            - name: Build
              env:
                  BASE_PATH: '/${{ github.event.repository.name }}'
                  PUBLIC_RESUME_STORAGE_BASE_URL: ${{ secrets.RESUME_STORAGE_BASE_URL }}
                  PUBLIC_RESUME_STORAGE_PREFIX: ${{ secrets.RESUME_STORAGE_PREFIX }}
              run: |
                  pnpm run build
            - name: Upload Artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: 'build/'
    deploy:
        needs: build_site
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
